import { GoogleGenAI, Modality } from "@google/genai";

const API_KEY = process.env.API_KEY;
if (!API_KEY) {
  // In a real app, you might show a more user-friendly error or disable functionality.
  // For this example, we assume the key is present.
  console.warn("API_KEY environment variable is not set. App will not function correctly.");
}
const ai = new GoogleGenAI({ apiKey: API_KEY! });

/**
 * Generates a product image using the 'imagen-4.0-generate-001' model.
 * @param prompt - The user's description of the product.
 * @returns A base64 encoded string of the generated JPEG image.
 */
export const generateProductImage = async (prompt: string): Promise<string> => {
  const fullPrompt = `professional product photography of ${prompt}, clean white background, high resolution, studio lighting, photorealistic`;
  
  const response = await ai.models.generateImages({
    model: 'imagen-4.0-generate-001',
    prompt: fullPrompt,
    config: {
      numberOfImages: 1,
      outputMimeType: 'image/jpeg',
      aspectRatio: '1:1',
    },
  });

  if (!response.generatedImages || response.generatedImages.length === 0) {
    throw new Error("Image generation failed, no images were returned.");
  }

  return response.generatedImages[0].image.imageBytes;
};

/**
 * Applies a logo to a mockup image using the 'gemini-2.5-flash-image' model.
 * @param mockupImage - The base mockup image data and mime type.
 * @param logoImage - The logo image data and mime type.
 * @param prompt - The user's instructions for placing the logo.
 * @returns A base64 encoded string of the final PNG image.
 */
export const applyLogoToImage = async (
  mockupImage: { data: string; mimeType: string },
  logoImage: { data: string; mimeType: string },
  prompt: string
): Promise<string> => {
  const fullPrompt = `You are an expert graphic designer. Your task is to realistically place a logo onto a product mockup.
  The first image provided is the product mockup. The second image is the logo.
  Follow these instructions precisely: ${prompt}.
  Ensure the logo's perspective, lighting, and texture match the product mockup for a photorealistic result.
  Do not add any other elements or change the background. Output only the final edited image.`;
  
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            data: mockupImage.data,
            mimeType: mockupImage.mimeType,
          },
        },
        {
          inlineData: {
            data: logoImage.data,
            mimeType: logoImage.mimeType,
          },
        },
        {
          text: fullPrompt,
        },
      ],
    },
    config: {
      responseModalities: [Modality.IMAGE],
    },
  });

  for (const part of response.candidates[0].content.parts) {
    if (part.inlineData) {
      return part.inlineData.data;
    }
  }

  throw new Error("No image was generated by the edit request.");
};
